Repository line/create-liff-app, pull requests merged in 2025-01, with the labels that each got.

#34 Add release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: type: maintenance

#35 Add publish workflow
  .github/workflows/publish.yml
Labels: type: maintenance

#36 add always-auth: true
  .github/workflows/publish.yml
Labels: type: maintenance, skip-changelog

#38 add registry-url
  .github/workflows/publish.yml
Labels: type: maintenance

#39 add files in package.json
  package.json
Labels: type: maintenance

#41 Add templates in files
  package.json
Labels: type: bug

#40 Update release-drafter.yml
  .github/release-drafter.yml
Labels: type: maintenance

#43 Fix a broken template of React
  templates/react-ts/src/main.tsx
  templates/react/src/main.jsx
Labels: type: bug
